-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th7 13, 2022 lúc 09:47 AM
-- Phiên bản máy phục vụ: 10.4.21-MariaDB
-- Phiên bản PHP: 8.0.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `shop_db`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `products`
--

CREATE TABLE `products` (
  `id` int(100) NOT NULL,
  `name` varchar(100) NOT NULL,
  `author` varchar(50) NOT NULL,
  `category` varchar(50) NOT NULL,
  `publisher` varchar(50) DEFAULT NULL,
  `availability` int(5) DEFAULT NULL,
  `price` int(100) NOT NULL,
  `summary` varchar(10000) DEFAULT NULL,
  `image` varchar(100) NOT NULL,
  `year` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Đang đổ dữ liệu cho bảng `products`
--

INSERT INTO `products` (`id`, `name`, `author`, `category`, `publisher`, `availability`, `price`, `summary`, `image`, `year`) VALUES
(1, '\r\nSherlock Holmes – Tập 1', '\r\nConan Doyle', '\r\nTiểu Thuyết Trinh Thám', '\r\nNhà Xuất Bản Văn Học', 10, 100000, 'Tên tôi là Sherlock Holmes. Công việc của tôi là tìm hiểu những gì mà người khác không biết…” Đối với các độc giả yêu thích dòng văn trinh thám nói riêng cũng như những người yêu sách trên toàn thế giới nói chung thì không phải nói nhiều về sức hút của hai cái tên: nhà văn Conan Doyle và “đứa con tinh thần” của cả cuộc đời ông - Sherlock Holmes. Nhân vật Sherlock Holmes từ lâu đã trở thành nguồn cảm hứng cho hàng trăm, hàng ngàn tác phẩm ở nhiều loại hình nghệ thuật khác: từ âm nhạc, ca kịch đến điện ảnh… Bộ sách Sherlock Holmes toàn tập (Hộp 3 Tập) một lần nữa mang đến cho người đọc cơ hội được nhìn ngắm, ngưỡng mộ và đánh giá nhân vật độc đáo của nhà văn tài năng Conan Doyle. Chân dung cuộc đời, sự nghiệp và nhân cách của Sherlock Holmes chưa bao giờ được tái hiện chân thực, đầy đủ và sống động đến thế...Chỉ từ một giọt nước, người giỏi suy luận có thể đoán ra rất nhiều chuyện liên quan đến một thác nước hay một đại dương dù họ chưa bao giờ tận mắt nhìn thấy chúng.Như vậy, cuộc sống là một chuỗi mắt xích rộng lớn nhất của nó, nếu ta biết được một mắt xích. Như tất cả mọi khoa học khác, “suy đoán và phân tích” là một khoa học mà ta chỉ có thể làm chủ nó sau một quá trình nghiên cứu dài lâu, bền bỉ. Người mới đi vào lĩnh vực này nên bắt đầu bằng những vấn đề sơ đẳng: gặp bất kỳ ai, chỉ bằng vào sự quan sát, hãy cố tìm hiểu tiểu sử, nghề nghiệp hay thói quen của người ấy. Tuy có vẻ ấu trĩ nhưng thực ra sự thật này được rèn giũa các khả năng quan sát của ta và nó dạy cho ta biết cần phải nhìn thẳng vào đâu và phải tìm kiếm cái gì. Móng tay, những vết chai ở ngón trỏ và ngón cái, ống tay áo, đầu gối quần, dáng đi, cách đứng đều là những thứ nói lên nghề nghiệp của một con người…', '\nsherlock-holmes-1.jpg', 0),
(2, 'Signet Classics : The Origin of Species', 'Charles Darwin', 'Tiểu Thuyết', 'Penguin Random House UK', 20, 210000, 'Tác phẩm kinh điển của Charles Darwin đã bùng nổ trong cuộc tranh cãi công khai, cách mạng hóa quá trình khoa học và tiếp tục thay đổi quan điểm của chúng ta về thế giới. Rất ít cuốn sách khác đã tạo ra một cơn bão tranh cãi kéo dài như Nguồn gốc của các loài. Lý thuyết của Darwin cho rằng các loài có nguồn gốc từ các loài khác bằng một quá trình tiến hóa dần dần và mức độ trung bình của mỗi loài được nâng cao nhờ \"sự sống sót của những người khỏe mạnh nhất\" đã khuấy động cuộc tranh luận phổ biến đến mức sốt cao. Sự chấp nhận của nó đã cách mạng hóa quá trình khoa học.', 'Signet-Classics-The-Origin-of-Species.jpg', 0),
(3, 'The Fault In Our Stars', 'John Green', 'Tiểu Thuyết', 'Penguin Random House UK', 15, 150000, 'Một phiên bản màu đen nổi bật của cuốn sách bán chạy số 1 nhiều triệu USD, hiện là một bức tranh chuyển động chính với sự tham gia của Shailene Woodley và Ansel Elgort. \"Tôi đã yêu cách bạn chìm vào giấc ngủ: từ từ, rồi tất cả cùng một lúc.\" Bất chấp phép màu y học thu nhỏ khối u đã mua chuộc cô trong vài năm, Hazel chưa bao giờ là bất cứ thứ gì khác ngoài thiết bị đầu cuối, chương cuối cùng của cô được ghi sau khi chẩn đoán. Nhưng khi một cốt truyện tuyệt đẹp mang tên Augustus Waters bất ngờ xuất hiện tại Nhóm hỗ trợ trẻ em ung thư, câu chuyện của Hazel sắp được viết lại hoàn toàn.', 'the-fault-in-our-stars.jpg', 0),
(4, 'Me Before You', 'Jojo Moyes', 'Tiểu Thuyết', 'Penguin Random House UK', 28, 100000, 'Louisa Clark là một cô gái bình thường sống một cuộc sống cực kỳ bình thường - bạn trai ổn định, gia đình thân thiết - người hầu như không xa hơn ngôi làng nhỏ bé của họ. Cô nhận một công việc rất cần thiết là làm việc cho cựu Chủ nhân của Vũ trụ Will Traynor, người phải ngồi xe lăn sau một vụ tai nạn. Will luôn sống một cuộc đời hào sảng - những giao dịch lớn, những môn thể thao mạo hiểm, những chuyến du lịch khắp thế giới - và giờ anh ấy khá chắc chắn rằng mình không thể sống theo cách của mình ...', 'me-before-you.jpg', 0),
(5, 'Elon Musk: How The Billionaire CEO Of Spacex And Tesla Is Shaping Our Future', 'Ashlee Vance', 'Tâm Lý Học', 'Penguin Random House UK', 100, 90000, 'Trong Elon Musk: Tesla, SpaceX và Quest for a Fantastic Future, nhà báo công nghệ kỳ cựu Ashlee Vance đã cung cấp cái nhìn sâu sắc đầu tiên về cuộc đời và thời đại phi thường của doanh nhân táo bạo nhất Thung lũng Silicon. Được viết với sự tiếp cận độc quyền của Musk, gia đình và bạn bè của anh ấy, cuốn sách theo dõi hành trình của doanh nhân từ thời kỳ nuôi dạy khó khăn ở Nam Phi đến đỉnh cao của thế giới kinh doanh toàn cầu. Vance đã dành hơn 30 giờ để trò chuyện với Musk và phỏng vấn gần 300 người để kể những câu chuyện gây xôn xao về các công ty thay đổi thế giới của Musk: PayPal, Tesla Motors, SpaceX và SolarCity, và để mô tả một người đàn ông đã đổi mới ngành công nghiệp Mỹ và tạo ra sức mạnh mới mức độ đổi mới trong khi tạo ra nhiều kẻ thù trên đường đi.', 'Elon-Musk-How-The-Billionaire-CEO-Of-Spacex-And-Tesla-Is-Shaping-Our-Future.jpg', 0),
(6, 'The Immortal Life of Henrietta Lacks', 'Rebecca Skloot', 'Tiểu Thuyết', 'Pan Book Publisher', 13, 120000, 'Câu chuyện bán chạy nhất thế giới về một phụ nữ trẻ qua đời năm 1951 đã thay đổi ngành y học mãi mãi. . .', 'the-immortal-life-of-henrietta-lacks.jpg', 0),
(7, 'Lược sử thời gian', 'Stephen W. Hawking', 'Khoa học, Công nghệ, Kinh tế', 'Nhà xuất bản trẻ', 27, 300000, 'Cùng với Vũ trụ trong vỏ hạt dẻ, Lược sử thời gian được xem là cuốn sách nổi tiếng và phổ biến nhất về vũ trụ học của Stephen Hawking, liên tục được nằm trong danh mục sách bán chạy nhất của các tạp chí nổi tiếng thế giới.Lược sử thời gian là cuốn sử thi về sự ra đời, sự hình thành và phát triển của vũ trụ. Tác giả đưa vào tác phẩm của mình toàn bộ tiến bộ tiến trình khám phá của trí tuệ loài người trên nhiều lĩnh vực: Triết học, Vật lý, Thiên văn học…', 'luoc-su-thoi-gian.jpg', 0),
(8, 'Mật mã - Từ cổ điển đến lượng tử', 'Simon Singh', 'Khoa học, Công nghệ, Kinh tế', 'Nhà xuất bản trẻ', 12, 120000, 'Trong hàng ngàn năm, vua chúa cũng như các tướng lĩnh đều dựa vào mạng lưới thông tin liên lạc hiểu quả để cai trị đất nước và chỉ huy quân đội của mình. Đồng thời, tất cả họ đều ý thức được những hậu quả của việc để lọt thông tin của mình vào tay đối phương, để lộ những bí mật quý giá cho các nước thù địch cũng như hậu quả của sự phản bội cung cấp thông tin sống còn cho các lực lượng đối kháng. Chính nỗi lo sợ bị kẻ thù xem trộm đã thúc đẩy sự ra đời và phát triển của mật mã: đó là những kỹ thuật nhằm che giấu, ngụy trang thông tin, khiến cho chỉ những người cần được nhận mới có thề đọc được.', 'the-code-book.jpg', 0),
(9, 'Doraemon: Nobita ở xứ sở chó mèo', 'Fujiko F Fujio', 'Truyện Tranh', 'Nhà xuất bản Kim Đồng', 31, 20000, 'Truyện kể về tình bạn gắn bó giữa cậu bé Nobita loài người và chú chó Ichi, sau 1000 năm xa cách cả hai vẫn không quên người kia. Ở thế giới của mình, Nobita đã nhặt được một chú chó con đáng yêu và đặt tên là Ichi, không bao lâu sau Nobita và các bạn của mình phát hiện rất nhiều chó mèo bị bỏ rơi; thế nhưng mẹ của Nobita không cho phép cậu bé nuôi thú trong nhà. Nobita đã dùng cỗ máy thời gian của Doraemon để đưa tất cả về quá khứ - trước cả thời kỳ khủng long xuất hiện để bọn chó mèo có thể sống vui vẻ. Lúc Nobita, Doraemon và các bạn của mình quay lại thăm Ichi và những con vật khác thì bị cuốn vào một cơn lốc xoáy thời gian khiến thời gian thay đổi - cả bọn bước vào thế giới chó mèo 1000 năm sau - lúc này nơi đây đã trở thành một thành phố phồn hoa và thịnh vượng. Trải qua nhiều khó khăn và biến cố cùng với nhau, qua những hiểu lầm ban đầu, Nobita cùng Ichi cuối cùng đã nhận ra nhau.', 'doraemon-nobita-va-xu-so-cho-meo.jpg', 0),
(10, 'Kỷ nguyên Trí tuệ nhân tạo', 'Nhiều Nguồn', 'Khoa học, Công nghệ, Kinh tế', 'Nhà xuất bản Hồng Đức', 13, 132000, 'Trong cuộc sống hàng ngày của mỗi chúng ta, có bao nhiêu thời gian được dùng cho những công việc mưu sinh mang tính lặp đi lặp lại buồn tẻ, có bao nhiêu thời gian dùng cho việc đọc sách, học tập, sáng tạo, tư duy, giải trí và hưởng thụ? Một ngày của nhân viên văn phòng thành phố, ngoài thời gian dành cho ngủ nghỉ, thì có hơn 60% thời gian dành để cho giao tiếp xã giao và xử lý những công việc mưu sinh mang tính quy trình, chỉ có khoảng 10% thời gian dành cho bản thân. Ngày nay, các nhà nghiên cứu trong lĩnh vực khoa học công nghệ đang nỗ lực để cho máy móc có được “trí tuệ” giống như con người, đồng thời để cho hoạt động con người được “thông tin hóa”.', 'ky-nguyen-tri-tue-nhan-tao.jpg', 0),
(11, 'Code dạo ký sự', 'Phạm Huy Hoàng', 'Tâm Lý Học', 'Nhà xuất bản Dân Trí', 22, 50000, 'Với mong muốn chia sẻ kinh nghiệm học lập trình và các kỹ năng mà anh đã trải qua trong suốt quá trình học và làm việc với tư cách là người đi trước cũng như là một Developer Full Stack, nên anh đã quyết định xuất bản sách “Code dạo ký sự – lập trình viên đâu phải chỉ biết code”. Hiện tại, trên thị trường sách Việt Nam với chủ đề về IT nói chung và lập trình viên nói riêng đều rất khan hiếm, chủ yếu là dịch lại từ tác giả nước ngoài. Chúng ta đã quá mải mê vào những đầu sách dạng “Những cách làm giàu hay đại loại vậy” đã khiến chúng ta ảo tưởng phần nào về bản thân mà thật sự kỹ năng của bạn không cho phép để làm điều đó. Vì thế chúng ta cần những đầu sách để định hướng nghề nghiệp và xây dựng kiến thức thật vững chắc, khi đó bạn mới có thể nghĩ tới những điều tuyệt vời hơn trong tương lai. “Code dạo ký sự – lập trình viên đâu phải chỉ biết code” sẽ đem lại cho bạn điều đó.', 'code-dao-ky-tu.jpg', 0),
(12, 'Giáo trình Toán Logic', 'Ths. Hồ Anh Minh', 'Khoa học, Công nghệ, Kinh tế', 'Nhà xuất bản khoa học kỹ thuật', 21, 120000, 'Cuốn sách là tài liệu tham khảo hữu ích cho bạn đọc lĩnh vực toán Logic.', 'giao-trinh-toan-logic.jpg', 0),
(13, 'Sự tiến hóa của vật lý', 'Albert Enstein', 'Khoa học, Công nghệ, Kinh t', 'Nhà xuất bản trẻ', 40, 98000, 'Hoàn toàn không dùng đến sự phức tạp của toán học, A. Einstein và L. Infeld đã phác họa vô cùng rõ ràng và thuyết phục những bước tiến hóa quan trọng nhất của khoa học vật lý. Xuyên suốt quyển sách này chính là tầm quan trọng của việc quan sát, vì mọi hiện tượng quanh ta, dù là bình thường nhất, luôn chứa đựng vô vàn bí ẩn. Và chính những bí ẩn ấy lại là tiền đề cho sự tiến hóa của khoa học. Độc giả sẽ vô cùng bất ngờ khi khám phá rằng “lượng tử” cũng như “chuyển động”, nếu thật sự hiểu được “chuyển động” là gì.', 'su-tien-hoa-cua-vat-ly.jpg', 0),
(14, 'Tào Tháo', 'Nhiều nguồn', 'Lịch Sử', 'Nhà xuất bản Dân Trí', 50, 500000, 'Tào Tháo là nhân vật có tính cách phức tạp và nhiều hình tượng nhất trong lịch sử Trung Quốc. Vừa giảo hoạt gian trá, lại thẳng thắn chân thành; vừa khoan dung độ lượng, lại đa nghi khôn cùng; vừa hào sảng, lại hẹp hòi; khí phách anh hùng, tình cảm dạt dào; hành động tàn nhẫn, tâm địa Bồ Tát. Tào Tháo là một nghệ nhân Biến Diện tài tình, lúc thì mang gương mặt này, thoắt cái lật sang gương mặt khác. Có thể hợp nhất những tính cách phức tạp như vậy trong một con người, là điều vô cùng khó, vậy mà tất cả những thứ ấy đều hội tụ nơi ông. Dường như con người Tào Tháo là tổng hòa của mọi mâu thuẫn trên thế gian. Ông có rất nhiều cuốn sách nổi tiếng , các tác phẩm trong đó đều thể hiện những khát vọng, hoài bão chính trị đồng thời phản ánh sự khao khát người tài, quan điểm chống phá thế tộc môn đệ và áp chế cường hào.', 'sach-tao-thao.jpg', 0),
(15, 'Nghìn Lẻ Một Đêm', 'Nhiều Nguồn', 'Tiểu Thuyết văn học', 'Công ti cổ phần văn hóa Đông A', 41, 360000, 'Bắt nguồn từ một cuốn sách cổ tên là Hezār Afsān (Một ngàn truyện), pho sách đồ sộ Nghìn lẻ một đêm tập hợp những câu chuyện dân gian kỳ ảo có xuất xứ từ Ả Rập, Ba Tư và Hy Lạp, được lưu truyền bởi những người Ai Cập kể chuyện rong vào thế kỷ XII và XIII, có nội dung phong phú, chủ đề đa dạng và từ ngữ sáng sủa. Về nội dung, Nghìn lẻ một đêm mở ra một thế giới đa sắc màu với đủ các khuôn mặt từ thần tiên đến con người, từ nhà quý tộc đến người bình dân trong xã hội Ả Rập thời Trung cổ. Về nghệ thuật, tác phẩm có một kết cấu hết sức hoàn chỉnh, mạch truyện hấp dẫn với nhiều tình tiết kịch tính và bất ngờ, cùng ngôn ngữ kể chuyện điêu luyện. Kể từ khi xuất hiện, Nghìn lẻ một đêm sớm gây ảnh hưởng sâu rộng lên nền văn học nhân loại và truyền cảm hứng cho nhiều nhà văn nổi tiếng thế giới, như lời nhận xét của nhà văn Maxin Gorki: “Công trình dệt gấm bằng từ ngữ này xuất hiện từ thời tối cổ, những sợi tơ muôn màu của nó lan khắp bốn phương, phủ lên Trái Đất một tấm thảm từ ngữ đẹp lạ lùng”.', 'nghinle1dem.jpg', 0),
(16, 'Bá Tước Monte Cristo', 'Alexandre Dumas', 'Tiểu Thuyết Văn Học', 'Nhà xuất bản văn học', 32, 320000, 'Bá tước Monte Cristo lấy bối cảnh nước Pháp thế kỷ XIX lấp lánh xinh đẹp, nhưng đầy rẫy lọc lừa và những âm mưu toan tính cá nhân. Tất cả hiện lên giống như màn kịch trong nhà hát, khiến người ta kinh sợ. Nơi đó, tình người trở nên hiếm hoi. Chàng Edmond Dantès trẻ tuổi, tài hoa, có một tương lai hứa hẹn, hạnh phúc bên người vợ sắp cưới. Song chính trong ngày cưới của mình, Edmond bị vu oan giá họa và bị bắt nhốt bỏ ngục. Sống trong cảnh tù đầy đọa, bị cướp mất tình yêu và sự tự do, cuộc đời chàng trai trẻ dường như đã mất hết hy vọng, chỉ còn bóng tối vây quanh. Thế nhưng sau nhiều năm đằng đẵng, một người bạn tù đã giúp chàng vượt ngục. Từ đây bắt đầu cuộc báo thù đầy ly kì và bất ngờ của Edmond Dantès - nay đã là Bá tước Monte Cristo.', 'ba-tuoc-monte-cristo.jpg', 0),
(17, 'Bố già', 'Mario Puzo', 'Tiểu Thuyết Văn Học', 'Công ti cổ phần văn hóa Đông A', 33, 333000, 'Thế giới ngầm được phản ánh trong tiểu thuyết Bố Già là sự gặp gỡ giữa một bên là ý chí cương cường và nền tảng gia tộc chặt chẽ theo truyền thống mafia xứ Sicily với một bên là xã hội Mỹ nhập nhằng đen trắng, mảnh đất màu mỡ cho những cơ hội làm ăn bất chính hứa hẹn những món lợi kếch xù. Trong thế giới ấy, hình tượng Bố Già được tác giả dày công khắc họa đã trở thành bức chân dung bất hủ trong lòng người đọc. Từ một kẻ nhập cư tay trắng đến ông trùm tột đỉnh quyền uy, Don Vito Corleone là con rắn hổ mang thâm trầm, nguy hiểm khiến kẻ thù phải kiềng nể, e dè, nhưng cũng được bạn bè, thân quyến xem như một đấng toàn năng đầy nghĩa khí. Nhân vật trung tâm ấy đồng thời cũng là hiện thân của một pho triết lí rất “đời” được nhào nặn từ vốn sống của hàng chục năm lăn lộn giữa chốn giang hồ bao phen vào sinh ra tử, vì thế mà có ý kiến cho rằng “Bố Già là sự tổng hòa của mọi hiểu biết. Bố Già là đáp án cho mọi câu hỏi”.', 'bo-gia.jpg', 0),
(18, 'Nhà giả kim', 'Paulo Coelho', 'Tiểu Thuyết Văn Học', 'Nhã Nam', 34, 34000, 'Tất cả những trải nghiệm trong chuyến phiêu du theo đuổi vận mệnh của mình đã giúp Santiago thấu hiểu được ý nghĩa sâu xa nhất của hạnh phúc, hòa hợp với vũ trụ và con người. Tiểu thuyết Nhà giả kim của Paulo Coelho như một câu chuyện cổ tích giản dị, nhân ái, giàu chất thơ, thấm đẫm những minh triết huyền bí của phương Đông. Trong lần xuất bản đầu tiên tại Brazil vào năm 1988, sách chỉ bán được 900 bản. Nhưng, với số phận đặc biệt của cuốn sách dành cho toàn nhân loại, vượt ra ngoài biên giới quốc gia, Nhà giả kim đã làm rung động hàng triệu tâm hồn, trở thành một trong những cuốn sách bán chạy nhất mọi thời đại, và có thể làm thay đổi cuộc đời người đọc.', 'nha-gia-kim.jpg', 0),
(19, 'Đại dương đen', 'Đặng Hoàng Giang', 'Tiểu Thuyết', 'Nhã Nam', 35, 35000, 'Tôi sợ những cơn của mình, chúng xâm chiếm não bộ tôi, nhấn chìm lý trí của tôi, chúng phơi bày sự đau đớn, cô đơn, nỗi sầu thảm suốt những năm tháng niên thiếu của tôi, sự ám ảnh của bạo lực, của lẻ loi, của tức giận vì chẳng được ai giúp đỡ. Trong những giấc mơ, tôi thét lên với mọi người, cố gắng diễn đạt sự sợ hãi và tuyệt vọng của mình, nhưng không ai hiểu.” Đại dương đen là hành trình nhẫn nại của tác giả Đặng Hoàng Giang cùng người trầm cảm, kể cho chúng ta câu chuyện vừa dữ dội vừa tê tái về những số phận, mà vì định kiến và sự thiếu hiểu biết của chính gia đình và xã hội, đã bị tước đi quyền được sống với nhân phẩm, được cống hiến, được yêu thương và hạnh phúc. Là tiếng nói chia sẻ hiếm hoi với thế giới của người trầm cảm, là lời kêu gọi xóa bỏ định kiến xã hội, Đại dương đen đồng thời là công trình giáo dục tâm lý, cung cấp kiến thức căn bản về trầm cảm, hình hài nó thế nào, nó từ đâu tới, nó có thể phá hủy ra sao, có những phương thức trị liệu nào, và mỗi chúng ta có thể làm gì để những người không may mắn được sống an hòa với nhân phẩm của mình.', 'dai-duong-den.jpg', 0),
(20, 'Những tù nhân của địa lý', 'Tim Marshall', 'Tiểu Thuyết', 'Nhã Nam', 40, 400000, '“Khi chúng ta đang vươn tới những vì sao, chính bởi những thách thức đặt ra phía trước mà chúng ta có lẽ sẽ phải chung tay để ứng phó: du hành vào vũ trụ không phải với tư cách người Nga, người Trung Quốc hay người Mỹ, mà là những đại diện của nhân loại. Nhưng cho đến nay, mặc dù đã thoát khỏi sự kìm hãm của trọng lực, chúng ta vẫn đang bị giam giữ trong tâm trí của chính mình, bị giới hạn bởi sự nghi ngờ của mình về ‘kẻ khác’, và do đó bởi cuộc cạnh tranh chính yếu về tài nguyên. Phía trước chúng ta còn cả một chặng đường dài.”', 'nhung-tu-nhan-cua-dia-ly.jpg', 0),
(21, 'doremon', '', '', NULL, NULL, 20000, NULL, 'tải xuống (1).jpg', 0);

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `products`
--
ALTER TABLE `products`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
